In [ ]:
import pandas as pd
data = pd.read_csv('MovieData-2018-2020.csv')
data

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,A Quiet Place,PG-13,Drama,2018,"April 6, 2018 (United States)",7.5,456000.0,John Krasinski,Bryan Woods,Emily Blunt,United States,17000000.0,3.503204e+08,Paramount Pictures,90.0
1,Avengers: Infinity War,PG-13,Action,2018,"April 27, 2018 (United States)",8.4,897000.0,Anthony Russo,Christopher Markus,Robert Downey Jr.,United States,321000000.0,2.048360e+09,Marvel Studios,149.0
2,Deadpool 2,R,Action,2018,"May 18, 2018 (United States)",7.7,505000.0,David Leitch,Rhett Reese,Ryan Reynolds,Canada,110000000.0,7.864705e+08,Twentieth Century Fox,119.0
3,Bohemian Rhapsody,PG-13,Biography,2018,"November 2, 2018 (United States)",7.9,476000.0,Bryan Singer,Anthony McCarten,Rami Malek,United Kingdom,52000000.0,9.119026e+08,Twentieth Century Fox,134.0
4,Black Panther,PG-13,Action,2018,"February 16, 2018 (United States)",7.3,661000.0,Ryan Coogler,Ryan Coogler,Chadwick Boseman,United States,200000000.0,1.347598e+09,Marvel Studios,134.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,Love by Drowning,R,Drama,2020,"November 6, 2020 (United States)",NaN,NaN,Justin Kreinbrink,C.E. Poverman,Nicky Whelan,United States,1000000.0,NaN,Dow Jazz Films,121.0
270,The Robinsons,NaN,Action,2020,"November 10, 2020 (United States)",NaN,NaN,Directors,Aleks Alifirenko Jr.,Billy Hartmann,United States,10000.0,NaN,NaN,90.0
271,More to Life,NaN,Drama,2020,"October 23, 2020 (United States)",3.1,18.0,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,NaN,NaN,90.0
272,Saving Mbango,NaN,Drama,2020,"April 27, 2020 (Cameroon)",5.7,29.0,Nkanya Nkwai,Lynno Lovert,Onyama Laura,United States,58750.0,NaN,Embi Productions,NaN
273,It's Just Us,NaN,Drama,2020,"October 1, 2020 (United States)",NaN,NaN,James Randall,James Randall,Christina Roz,United States,15000.0,NaN,NaN,120.0

In [ ]:
# Stratifed data by genre
from sklearn.model_selection import train_test_split

_, stratified_sample = train_test_split(
    data,
    test_size=0.3,
    stratify=data['genre'],
    random_state=4
)

stratified_sample

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
16,The Predator,R,Action,2018,"September 14, 2018 (United States)",5.3,120000.0,Shane Black,Fred Dekker,Boyd Holbrook,United States,88000000.0,1.605421e+08,Twentieth Century Fox,107.0
72,First Man,PG-13,Biography,2018,"October 12, 2018 (United States)",7.3,176000.0,Damien Chazelle,Josh Singer,Ryan Gosling,United States,59000000.0,1.057132e+08,Universal Pictures,141.0
27,Instant Family,PG-13,Comedy,2018,"November 16, 2018 (United States)",7.3,97000.0,Sean Anders,Sean Anders,Mark Wahlberg,United States,48000000.0,1.205562e+08,Closest to the Hole Productions,118.0
157,Spider-Man: Far from Home,PG-13,Action,2019,"July 2, 2019 (United States)",7.5,359000.0,Jon Watts,Chris McKenna,Tom Holland,United States,160000000.0,1.131928e+09,Columbia Pictures,129.0
195,Five Feet Apart,PG-13,Drama,2019,"March 15, 2019 (United States)",7.2,51000.0,Justin Baldoni,Mikki Daughtry,Haley Lu Richardson,United States,7000000.0,9.152780e+07,CBS Films,116.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,Mine 9,Not Rated,Drama,2019,"May 19, 2020 (Poland)",6.4,4400.0,Eddie Mensore,Eddie Mensore,Terry Serpico,United States,350000.0,2.264210e+05,Emphatic Films,83.0
154,Fast & Furious Presents: Hobbs & Shaw,PG-13,Action,2019,"August 2, 2019 (United States)",6.4,184000.0,David Leitch,Chris Morgan,Dwayne Johnson,United States,200000000.0,7.590569e+08,Chris Morgan Productions,137.0
224,Shaft,R,Action,2019,"June 14, 2019 (United States)",6.4,48000.0,Tim Story,Ernest Tidyman,Samuel L. Jackson,United States,35000000.0,2.136022e+07,Davis Entertainment,111.0
76,Replicas,PG-13,Drama,2018,"January 11, 2019 (United States)",5.5,34000.0,Jeffrey Nachmanoff,Chad St. John,Keanu Reeves,United Kingdom,30000000.0,9.330075e+06,Company Films,107.0
146,Fighting with My Family,PG-13,Biography,2019,"February 22, 2019 (United States)",7.1,71000.0,Stephen Merchant,Stephen Merchant,Dwayne Johnson,United Kingdom,11000000.0,4.081192e+07,Metro-Goldwyn-Mayer (MGM),108.0

In [ ]:
# Melihat jumlah data setiap genre
data["genre"].value_counts()

genre
Action       88
Comedy       45
Drama        38
Biography    29
Animation    23
Adventure    19
Horror       15
Crime        12
Fantasy       3
Name: count, dtype: int64

In [ ]:
# Mengambil 30 data teratas
sample = stratified_sample.head(30)
sample

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
160,It Chapter Two,R,Drama,2019,"September 6, 2019 (United States)",6.5,222000.0,Andy Muschietti,Stephen King,Jessica Chastain,United States,79000000.0,4.730932e+08,New Line Cinema,169.0
222,Dumbo,PG,Adventure,2019,"March 29, 2019 (United States)",6.3,69000.0,Tim Burton,Ehren Kruger,Colin Farrell,United States,170000000.0,3.532846e+08,Walt Disney Pictures,112.0
144,Once Upon a Time... In Hollywood,R,Comedy,2019,"July 26, 2019 (United States)",7.6,603000.0,Quentin Tarantino,Quentin Tarantino,Leonardo DiCaprio,United States,90000000.0,3.745658e+08,Columbia Pictures,161.0
152,John Wick: Chapter 3 - Parabellum,R,Action,2019,"May 17, 2019 (United States)",7.4,296000.0,Chad Stahelski,Derek Kolstad,Keanu Reeves,United States,75000000.0,3.272818e+08,Lionsgate,130.0
181,Rocketman,R,Biography,2019,"May 31, 2019 (United States)",7.3,153000.0,Dexter Fletcher,Lee Hall,Taron Egerton,United Kingdom,40000000.0,1.951793e+08,Paramount Pictures,121.0
229,Blinded by the Light,PG-13,Comedy,2019,"August 16, 2019 (United States)",6.9,22000.0,Gurinder Chadha,Sarfraz Manzoor,Billy Barratt,United Kingdom,15000000.0,1.809669e+07,New Line Cinema,118.0
163,Ford v Ferrari,PG-13,Action,2019,"November 15, 2019 (United States)",8.1,323000.0,James Mangold,Jez Butterworth,Matt Damon,United States,97600000.0,2.255082e+08,Chernin Entertainment,152.0
250,The Prodigy,R,Fantasy,2019,"February 8, 2019 (United States)",5.9,24000.0,Nicholas McCarthy,Jeff Buhler,Taylor Schilling,United States,6000000.0,2.115026e+07,Orion Pictures,92.0
201,The Addams Family,PG,Animation,2019,"October 11, 2019 (United States)",5.8,31000.0,Greg Tiernan,Matt Lieberman,Oscar Isaac,Canada,24000000.0,2.037836e+08,Metro-Goldwyn-Mayer (MGM),86.0
125,Second Act,PG-13,Comedy,2018,"December 21, 2018 (United States)",5.8,24000.0,Peter Segal,Justin Zackham,Jennifer Lopez,United States,16000000.0,7.229407e+07,Huayi Brothers,103.0
155,Captain Marvel,PG-13,Action,2019,"March 8, 2019 (United States)",6.8,478000.0,Anna Boden,Anna Boden,Brie Larson,United States,160000000.0,1.128463e+09,Walt Disney Pictures,123.0
127,The Possession of Hannah Grace,R,Horror,2018,"November 30, 2018 (United States)",5.2,20000.0,Diederik Van Rooijen,Brian Sieve,Shay Mitchell,United States,7700000.0,4.301653e+07,Screen Gems,86.0
174,Dora and the Lost City of Gold,PG,Adventure,2019,"August 9, 2019 (United States)",6.1,27000.0,James Bobin,Nicholas Stoller,Isabela Merced,United States,49000000.0,1.196826e+08,Paramount Players,102.0
171,Downton Abbey,PG,Drama,2019,"September 20, 2019 (United States)",7.4,43000.0,Michael Engler,Julian Fellowes,Stephen Campbell Moore,United Kingdom,13000000.0,2.378600e+08,Carnival Film & Television,122.0
265,The Call of the Wild,PG,Adventure,2020,"February 21, 2020 (United States)",6.8,42000.0,Chris Sanders,Michael Green,Harrison Ford,Canada,135000000.0,1.111055e+08,20th Century Studios,100.0
177,The Lion King,PG,Animation,2019,"July 19, 2019 (United States)",6.9,222000.0,Jon Favreau,Jeff Nathanson,Donald Glover,United States,260000000.0,1.670728e+09,Walt Disney Pictures,118.0
105,Christopher Robin,PG,Adventure,2018,"August 3, 2018 (United States)",7.3,72000.0,Marc Forster,A.A. Milne,Ewan McGregor,United Kingdom,75000000.0,1.977444e+08,2DUX²,104.0
25,Mamma Mia! Here We Go Again,PG-13,Comedy,2018,"July 20, 2018 (United States)",6.6,85000.0,Ol Parker,Ol Parker,Lily James,United Kingdom,75000000.0,3.956182e+08,Universal Pictures,114.0
185,Long Shot,R,Comedy,2019,"May 3, 2019 (United States)",6.8,101000.0,Jonathan Levine,Dan Sterling,Charlize Theron,United States,40000000.0,5.387381e+07,Summit Entertainment,125.0
208,The Secret Life of Pets 2,PG,Animation,2019,"June 7, 2019 (United States)",6.5,55000.0,Chris Renaud,Brian Lynch,Patton Oswalt,United States,80000000.0,4.300513e+08,Universal Pictures,86.0
130,Winchester,PG-13,Biography,2018,"February 2, 2018 (United States)",5.5,32000.0,Michael Spierig,Tom Vaughan,Helen Mirren,Australia,3500000.0,4.401959e+07,CBS Films,99.0
46,The Hate U Give,PG-13,Crime,2018,"October 19, 2018 (United States)",7.5,33000.0,George Tillman Jr.,Audrey Wells,Amandla Stenberg,United States,23000000.0,3.493401e+07,Fox 2000 Pictures,133.0
1,Avengers: Infinity War,PG-13,Action,2018,"April 27, 2018 (United States)",8.4,897000.0,Anthony Russo,Christopher Markus,Robert Downey Jr.,United States,321000000.0,2.048360e+09,Marvel Studios,149.0
183,Toy Story 4,G,Animation,2019,"June 21, 2019 (United States)",7.7,217000.0,Josh Cooley,John Lasseter,Tom Hanks,United States,200000000.0,1.073395e+09,Pixar Animation Studios,100.0
5,Hereditary,R,Drama,2018,"June 8, 2018 (United States)",7.3,259000.0,Ari Aster,Ari Aster,Toni Collette,United States,10000000.0,8.023966e+07,PalmStar Media,127.0
223,The Hustle,PG-13,Comedy,2019,"May 10, 2019 (United States)",5.4,51000.0,Chris Addison,Stanley Shapiro,Anne Hathaway,United States,21000000.0,9.501704e+07,Metro-Goldwyn-Mayer (MGM),93.0
104,Gotti,R,Biography,2018,"June 14, 2018 (Hungary)",4.7,14000.0,Kevin Connolly,Leo Rossi,John Travolta,Canada,10000000.0,6.412349e+06,Emmett/Furla/Oasis Films (EFO Films),112.0
195,Five Feet Apart,PG-13,Drama,2019,"March 15, 2019 (United States)",7.2,51000.0,Justin Baldoni,Mikki Daughtry,Haley Lu Richardson,United States,7000000.0,9.152780e+07,CBS Films,116.0
176,The Best of Enemies,PG-13,Biography,2019,"April 5, 2019 (United States)",7.2,13000.0,Robin Bissell,Robin Bissell,Taraji P. Henson,United States,10000000.0,1.020981e+07,Astute Films,133.0
209,The Curse of la Llorona,R,Horror,2019,"April 19, 2019 (United States)",5.3,43000.0,Michael Chaves,Mikki Daughtry,Linda Cardellini,United States,9000000.0,1.231337e+08,New Line Cinema,93.0

In [ ]:
# Menghitung rata rata budget dan standar deviasi
x_bar = sample['budget'].mean() / 1000000
s = sample['budget'].std() / 1000000

print("Rata-rata Budget : {:.2f} juta".format(x_bar))
print("Standar Deviasi : {:.2f} juta".format(s))

Rata-rata Budget : 70.73 juta
Standar Deviasi : 80.68 juta

MENGHITUNG ESTIMASI

In [25]:
import scipy.stats as stats
import math

# Specify sample mean (x_bar), sample standard deviation (s), sample size (n) and confidence level
x_bar = 70.73
s = 80.68
n = 30
confidence_level = 0.95

# Calculate alpha, degrees of freedom (df), the critical t-value, and the margin of error
alpha = (1-confidence_level)
df = n - 1
standard_error = s/math.sqrt(n)
critical_t = stats.t.ppf(1-alpha/2, df)
margin_of_error = critical_t * standard_error

# Calculate the lower and upper bound of the confidence interval
lower_bound = x_bar - margin_of_error
upper_bound = x_bar + margin_of_error

# Print the results
print("Critical t-value: {:.3f}".format(critical_t))
print("Margin of Error: {:.3f}".format(margin_of_error))
print("Confidence Interval: [{:.3f},{:.3f}]".format(lower_bound,upper_bound))
print("The {:.1%} confidence interval for the population mean is:".format(confidence_level))
print("between {:.3f} and {:.3f}".format(lower_bound,upper_bound))

Critical t-value: 2.045
Margin of Error: 30.126
Confidence Interval: [40.604,100.856]
The 95.0% confidence interval for the population mean is:
between 40.604 and 100.856